---
- hosts: all
  vars:
    HASHICORP_ZIP_FILE: "{{syno_package_name}}_{{hashicorp_app_version}}_{{hashicorp_app_os}}_{{hashicorp_app_arch}}.zip"
    HASHICORP_APP_URL: "https://releases.hashicorp.com/{{syno_package_name}}/{{hashicorp_app_version}}/{{HASHICORP_ZIP_FILE}}"
  become: yes
  gather_facts: yes

  pre_tasks:

  - name: Debug
    debug:
      msg: "Going to download: {{HASHICORP_APP_URL}}"

  - name: Update apt cache if needed.
    apt: update_cache=yes cache_valid_time=3600

  - name: Get software for apt repository management.
    apt:
      name:
        - python3
        - python3-pip
        - cifs-utils
        - git
      state: present

  - name: "Check existence Synology Packaging build scripts"
    stat:
      path: /toolkit/pkgscripts-ng
    register: stat_pkgscripts

  - name: "Pull the Synology Packaging build scripts Git repository"
    git:
      repo: 'https://github.com/SynologyOpenSource/pkgscripts-ng.git'
      dest: /toolkit/pkgscripts-ng
      version: master
    when: not stat_pkgscripts.stat.exists

  - name: "Checkout the DSM 7.0 scripts"
    shell:
      chdir: /toolkit/pkgscripts-ng
      cmd: git checkout DSM7.0

  - name: "Check existence of avoton chroot environment"
    stat:
      path: "/toolkit/build_env/ds.avoton-7.0"
    register: stat_reg_ds_build_target_architecture_name

  - name: "Deploy the avoton chroot build environment"
    shell:
      chdir: /toolkit/pkgscripts-ng 
      cmd: ./EnvDeploy -v 7.0 -p avoton
    when: not stat_reg_ds_build_target_architecture_name.stat.exists

  - name: "Make sure the hashicorp app syno prebuilt exists."
    ansible.builtin.file:
      path: /toolkit/prebuilt/{{syno_package_name}}
      state: directory

  - name: "Pull the Synology ATVANZT Build Git repository"
    git:
      repo: 'https://github.com/atvanzt/synology.git'
      dest: "/toolkit/synology_{{syno_package_name}}_package_sources"
      version: develop 

  - name: "Copy Synology Hashicorp app package environment into Synology build toolkit for DSM 7.0"
    ansible.builtin.copy:
      src: "/toolkit/synology_{{syno_package_name}}_package_sources/synology/source"
      dest: /toolkit
      directory_mode:
      remote_src: yes

  - name: "Create the bin directory for the Hashicorp app binary" 
    ansible.builtin.file:
      path: "/toolkit/source/{{syno_package_name}}/package/bin"
      state: directory
 
  - name: "Download and unarchive Hashicorp released archive directly into the Synology packaging environment setup."
    ansible.builtin.unarchive:
      src: "{{HASHICORP_APP_URL}}" 
      dest: "/toolkit/source/{{syno_package_name}}/package/bin"
      remote_src: yes

  - name: "Inject correct Hashicorp app name into synology package INFO"
    ansible.builtin.replace:
      path: "/toolkit/source/{{syno_package_name}}/INFO.sh"
      regexp: '{put_synology_package_name_here}'
      replace: "{{syno_package_name}}"

  - name: "Inject correct Hashicorp app version number into synology package INFO"
    ansible.builtin.replace:
      path: "/toolkit/source/{{syno_package_name}}/INFO.sh"
      regexp: '{put_synology_package_version_here}'
      replace: "{{hashicorp_app_version}}_{{hashicorp_app_os}}_{{hashicorp_app_arch}}"

  - name: "Inject correct Hashicorp app display name into synology package INFO"
    ansible.builtin.replace:
      path: "/toolkit/source/{{syno_package_name}}/INFO.sh"
      regexp: '{put_synology_package_displayname_here}'
      replace: "{{syno_package_display_name}}"

  - name: "Inject correct Hashicorp app description into synology package INFO"
    ansible.builtin.replace:
      path: "/toolkit/source/{{syno_package_name}}/INFO.sh"
      regexp: '{put_synology_package_description_here}'
      replace: "{{syno_package_description}}"
      
  - name: "Execute the Synology build command to create the synology Hashicorp package."
    shell:
      chdir: /toolkit/pkgscripts-ng
      cmd: "./PkgCreate.py -v 7.0 -p avoton {{syno_package_name}}"

  - name: Set the release version tag
    set_fact:
      release_version_tag: "{{syno_package_name}}_{{hashicorp_app_version}}_{{hashicorp_app_os}}_{{hashicorp_app_arch}}"

  - name: Get the latest release when available 
    ansible.builtin.uri:
      url: "https://api.github.com/repos/atvanzt/synology/releases/tags/{{ release_version_tag }}"
      method: GET
      headers:
        Accept: "application/vnd.github+json"
        Authorization: "Bearer {{gh_access_token}}"
        X-GitHub-Api-Version: "2022-11-28" 
      status_code: [200, 404]
    register: release_tag_response
     
  - name: Create release
    ansible.builtin.uri:
      url: "https://api.github.com/repos/atvanzt/synology/releases"
      method: POST
      headers:
        Accept: "application/vnd.github+json"
        Authorization: "Bearer {{gh_access_token}}"
        X-GitHub-Api-Version: "2022-11-28" 
      body: {"tag_name":"{{ release_version_tag }}","target_commitish":"master","name":"{{ release_version_tag }}","body":"Hashicorp release notes: https://github.com/hashicorp/{{ syno_package_name }}/releases/tag/v{{ hashicorp_app_version }}","draft":false,"prerelease":false,"generate_release_notes":false}
      body_format: json
      status_code: 201
    register: release_info
    when: not release_tag_response == 200