---
- hosts: all
  vars:
    NOMAD_VERSION: 1.4.4
    PACKAGE_VERSION: "{{NOMAD_VERSION}}-1000"
    OS: linux
    ARCH: amd64
    NOMAD_ZIP_FILE: nomad_{{NOMAD_VERSION}}_{{OS}}_{{ARCH}}.zip	
    NOMAD_URL: "https://releases.hashicorp.com/nomad/{{NOMAD_VERSION}}/{{NOMAD_ZIP_FILE}}"
  become: yes
  gather_facts: yes

  pre_tasks:

  - name: Debug
    debug:
      msg: First start {{NOMAD_URL}}

  - name: Update apt cache if needed.
    apt: update_cache=yes cache_valid_time=3600

  - name: Get software for apt repository management.
    apt:
      name:
        - python3
        - python3-pip
        - cifs-utils
        - git
      state: present

  - name: "Check existence Synology Packaging build scripts"
    stat:
      path: /toolkit/pkgscripts-ng
    register: stat_pkgscripts

  - name: "Pull the Synology Packaging build scripts Git repository"
    git:
      repo: 'https://github.com/SynologyOpenSource/pkgscripts-ng.git'
      dest: /toolkit/pkgscripts-ng
      version: master
    when: not stat_pkgscripts.stat.exists

  - name: "Checkout the DSM 7.0 scripts"
    shell:
      chdir: /toolkit/pkgscripts-ng
      cmd: git checkout DSM7.0

  - name: "Check existence of avoton chroot environment"
    stat:
      path: "/toolkit/build_env/ds.avoton-7.0"
    register: stat_reg_ds_build_target_architecture_name

  - name: "Deploy the avoton chroot build environment"
    shell:
      chdir: /toolkit/pkgscripts-ng 
      cmd: ./EnvDeploy -v 7.0 -p avoton
    when: not stat_reg_ds_build_target_architecture_name.stat.exists

  - name: "Make sure the nomad prebuilt exists."
    ansible.builtin.file:
      path: /toolkit/prebuilt/nomad
      state: directory

  - name: "Download and unarchive nomad released archive"
    ansible.builtin.unarchive:
      src: "{{NOMAD_URL}}" 
      dest: /toolkit/prebuilt/nomad
      remote_src: yes
