---
- hosts: all
  vars:
    NOMAD_VERSION: 1.5.0
    PACKAGE_VERSION: "{{NOMAD_VERSION}}-1000"
    OS: linux
    ARCH: amd64
    NOMAD_ZIP_FILE: nomad_{{NOMAD_VERSION}}_{{OS}}_{{ARCH}}.zip	
    NOMAD_URL: "https://releases.hashicorp.com/nomad/{{NOMAD_VERSION}}/{{NOMAD_ZIP_FILE}}"
  become: yes
  gather_facts: yes

  pre_tasks:

  - name: Debug
    debug:
      msg: First start {{NOMAD_URL}}

  - name: Update apt cache if needed.
    apt: update_cache=yes cache_valid_time=3600

  - name: Get software for apt repository management.
    apt:
      name:
        - python3
        - python3-pip
        - cifs-utils
        - git
      state: present

  - name: "Check existence Synology Packaging build scripts"
    stat:
      path: /toolkit/pkgscripts-ng
    register: stat_pkgscripts

  - name: "Pull the Synology Packaging build scripts Git repository"
    git:
      repo: 'https://github.com/SynologyOpenSource/pkgscripts-ng.git'
      dest: /toolkit/pkgscripts-ng
      version: master
    when: not stat_pkgscripts.stat.exists

  - name: "Checkout the DSM 7.0 scripts"
    shell:
      chdir: /toolkit/pkgscripts-ng
      cmd: git checkout DSM7.0

  - name: "Check existence of avoton chroot environment"
    stat:
      path: "/toolkit/build_env/ds.avoton-7.0"
    register: stat_reg_ds_build_target_architecture_name

  - name: "Deploy the avoton chroot build environment"
    shell:
      chdir: /toolkit/pkgscripts-ng 
      cmd: ./EnvDeploy -v 7.0 -p avoton
    when: not stat_reg_ds_build_target_architecture_name.stat.exists

  - name: "Make sure the nomad prebuilt exists."
    ansible.builtin.file:
      path: /toolkit/prebuilt/nomad
      state: directory

  - name: "Pull the Synology Nomad ATVANZT Build Git repository"
    git:
      repo: 'https://github.com/gokkep/test_synology_builder.git'
      dest: /toolkit/synology_nomad_package_sources
      version: develop 

  - name: "Copy Synology Nomad package environment into Synology build toolkit for DSM 7.0"
    ansible.builtin.copy:
      src: /toolkit/synology_nomad_package_sources/synology/source
      dest: /toolkit
      directory_mode:
      remote_src: yes

  - name: "Create the bin directory for the nomad binairy" 
    ansible.builtin.file:
      path: /toolkit/source/nomad/package/bin
      state: directory
 
  - name: "Download and unarchive nomad released archive directly into the Synology packaging environment setup for nomad."
    ansible.builtin.unarchive:
      src: "{{NOMAD_URL}}" 
      dest: /toolkit/source/nomad/package/bin
      remote_src: yes

  - name: "Inject correct nomad version number for name nomad synology package INFO"
    ansible.builtin.lineinfile:
      path: /toolkit/source/nomad
      search_string: '{put_synology_package_version_here}'
      line: {{PACKAGE_VERSION}}

  - name: "Execute the Synology build command to create the synology nomad package."
    shell:
      chdir: /toolkit/pkgscripts-ng
      cmd: ./PkgCreate.py --v 7.0 -p avoton nomad
