
name: Test deployment on a Synology NAS using Ansible

env:
  # Use the same ssh-agent socket value across all jobs
  # Useful when a GH action is using SSH behind-the-scenes
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  run-playbook:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Start ssh-agent but set it to use the same ssh_auth_sock value.
    # The agent will be running in all steps after this, so it
    # should be one of the first.
      - name: Setup SSH passphrase
        env:
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE_ATV01}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY_ATV01}}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null
          
    # Debug print out the added identities. This will prove SSH_AUTH_SOCK
    # is persisted across job steps
      - name: Print ssh-add identities
        run: 
          ssh-add -l
          
    # Create Ansible inventory file with secrets using heredoc
      - name: Create Ansible inventory file
        run: |
          cat > inventory_atv01 <<DELIMITER 
            ansible_port=5000 ansible_ssh_private_key=id_rsa_ansible_atv01
          DELIMITER
        env:
          ATV01_HOST_IP4_ADDRESS: ${{ secrets.ATV01_HOST_IP4_ADDRESS }}
          SSH_PORT_ATV01: ${{ secrets.SSH_PORT_ATV01 }}
          SSH_ANSIBLE_USER_ATV01: ${{ secrets.SSH_ANSIBLE_USER_ATV01 }}

    # Verify inventory
      - name: Verify inventory
        run:
          cat inventory_atv01